const assert = require("node:assert/strict");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const { fork } = require("node:child_process");

if (process.argv[2] === "child") {
  const dir = process.argv[3];
  const settings = require(path.join(dir, "services/settings.service.js"));
  const secrets = require(path.join(dir, "services/cryptoSecrets.js"));
  settings.getSettings(); // Worker loads settings before the web process creates a key.
  process.send({ ready: true });
  process.on("message", ({ operation, value }) => {
    try {
      process.send({ value: secrets[operation](value) });
    } catch (error) {
      process.send({ error: error.message });
    }
  });
} else {
  let failures = 0;
  function next(child) {
    return new Promise((resolve, reject) => {
      const timer = setTimeout(() => finish(new Error("Child response timed out")), 5000);
      const onExit = () => finish(new Error("Child exited before replying"));
      const onMessage = (value) => finish(null, value);
      function finish(error, value) {
        clearTimeout(timer);
        child.off("exit", onExit);
        child.off("message", onMessage);
        error ? reject(error) : resolve(value);
      }
      child.once("exit", onExit);
      child.once("message", onMessage);
    });
  }
  async function send(child, operation, value) {
    const result = next(child);
    child.send({ operation, value });
    return result;
  }
  async function scenario(name, run) {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), "portal-key-"));
    const children = [];
    fs.mkdirSync(path.join(dir, "services"));
    fs.mkdirSync(path.join(dir, "data"));
    for (const file of ["settings.service.js", "cryptoSecrets.js"]) {
      fs.copyFileSync(path.join(__dirname, "../services", file), path.join(dir, "services", file));
    }
    const settingsPath = path.join(dir, "data/settings.json");
    fs.writeFileSync(settingsPath, JSON.stringify({ unrelated: "preserve-me" }));
    async function start(role) {
      const child = fork(__filename, ["child", dir], {
        env: { ...process.env, PROCESS_ROLE: role },
        stdio: ["ignore", "ignore", "inherit", "ipc"],
      });
      children.push(child);
      assert.deepEqual(await next(child), { ready: true });
      return child;
    }
    try {
      await run({ start, settingsPath });
      console.log(`PASS ${name}`);
    } catch (error) {
      failures++;
      console.error(`FAIL ${name}: ${error.message}`);
    } finally {
      await Promise.all(children.map((child) => new Promise((resolve) => {
        if (child.exitCode !== null || child.signalCode !== null) return resolve();
        child.once("exit", resolve);
        child.kill();
      })));
      fs.rmSync(dir, { recursive: true, force: true });
    }
  }
  (async () => {
    await scenario("worker-first startup preserves the shared key and password", async ({ start, settingsPath }) => {
      const worker = await start("worker");
      const web = await start("web");
      assert.ok(!(await send(web, "getKeyBuffer", { allowCreate: true })).error);
      const encrypted = await send(web, "encryptSecret", "supplied-password");
      assert.ok(encrypted.value?.startsWith("v1:"), encrypted.error);
      const before = fs.readFileSync(settingsPath, "utf8");
      const decrypted = await send(worker, "decryptSecret", encrypted.value);
      assert.equal(decrypted.value, "supplied-password", decrypted.error);
      assert.equal(fs.readFileSync(settingsPath, "utf8"), before);
      const restartedWorker = await start("worker");
      assert.equal((await send(restartedWorker, "decryptSecret", encrypted.value)).value, "supplied-password");
      assert.equal(JSON.parse(before).unrelated, "preserve-me");
    });
    await scenario("worker never creates a missing shared key", async ({ start, settingsPath }) => {
      const worker = await start("worker");
      const before = fs.readFileSync(settingsPath, "utf8");
      assert.ok((await send(worker, "encryptSecret", "password")).error);
      assert.equal(fs.readFileSync(settingsPath, "utf8"), before);
    });
    await scenario("missing key cannot be generated by ordinary encryption or decryption", async ({ start, settingsPath }) => {
      const web = await start("web");
      const before = fs.readFileSync(settingsPath, "utf8");
      assert.ok((await send(web, "encryptSecret", "password")).error);
      assert.equal(fs.readFileSync(settingsPath, "utf8"), before);
      const cipher = "v1:" + Buffer.alloc(12).toString("base64") + ":" + Buffer.alloc(16).toString("base64") + ":YQ==";
      assert.ok((await send(web, "decryptSecret", cipher)).error);
      assert.equal(fs.readFileSync(settingsPath, "utf8"), before);
    });
    for (const value of [null, [], "damaged", 42, false]) {
      await scenario(`non-object settings ${JSON.stringify(value)} are not rewritten`, async ({ start, settingsPath }) => {
        const web = await start("web");
        const before = JSON.stringify(value);
        fs.writeFileSync(settingsPath, before);
        const result = await send(web, "getKeyBuffer", { allowCreate: true });
        assert.match(result.error || "", /settings.*object/i);
        assert.equal(fs.readFileSync(settingsPath, "utf8"), before);
      });
    }
    await scenario("invalid persisted key is not replaced", async ({ start, settingsPath }) => {
      fs.writeFileSync(settingsPath, JSON.stringify({ MUTUAL_AID_ENCRYPTION_KEY: "damaged" }));
      const web = await start("web");
      assert.ok((await send(web, "getKeyBuffer", { allowCreate: true })).error);
      assert.equal(JSON.parse(fs.readFileSync(settingsPath)).MUTUAL_AID_ENCRYPTION_KEY, "damaged");
    });
    await scenario("encryption fails when the key cannot be saved", async ({ start, settingsPath }) => {
      const web = await start("web");
      fs.mkdirSync(settingsPath + ".tmp"); // Actual filesystem write failure.
      assert.ok((await send(web, "getKeyBuffer", { allowCreate: true })).error);
      assert.equal(JSON.parse(fs.readFileSync(settingsPath)).MUTUAL_AID_ENCRYPTION_KEY, undefined);
    });
    assert.equal(failures, 0, "cross-process regression failures");
  })().catch((error) => { console.error(error); process.exitCode = 1; });
}
